# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
branches:
  only:
    - master
os:
  - linux
  #  - osx
julia:
  - 1
#matrix:
#  allow_failures:
#    - julia: nightly
env:
  - GROUP=NNODE
  - GROUP=NNPDEHan
  - GROUP=NNPDENS
  - GROUP=NNPDE
  - GROUP=NNSTOPPINGTIME
  - GROUP=NNRODE
notifications:
  email: false
script: julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=false)'
